config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :users
  resources :travels, :except => [:new,:edit] do
    collection do
      get 'search', to: 'travels#search'
      get 'offer', to: 'travels#offer'
    end
  end

  match '/login', to: 'static_pages#login', via: 'get'
  match '/register', to: 'static_pages#register', via: 'get'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :travels
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages
  has_and_belongs_to_many :users
  belongs_to :travel
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :car
  has_many :conversations
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :conversations
  has_many :cars
  has_and_belongs_to_many :travels

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :null_session
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!

  def create
    if params[:is_simple_conversation]
      if Conversation.between(params[:sender_id],params[:recipient_id]).present?
        @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
      else
        @conversation = Conversation.new
        @conversation.sender = User.find(params[:sender_id])
        @conversation.recipient = User.find(params[:recipient_id])
        @conversation.is_simple_conversation = true
        @conversation.save
      end
    else
      @users_ids = params[:users_ids]
      @conversation = Conversation.new
      @users_ids.each do |user_id|
        @user = User.find(user_id)
        @conversation.users << @user
      end
      @conversation.is_simple_conversation = false
      @conversation.save
    end
    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @messages = @conversation.messages
    render json: @messages
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @conversation = Conversation.find(params[:conversation_id])
    @message = @conversation.messages.build(message_params)
    @message.user_id = current_user.id
    @message.save!
    render json: @message
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
  
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    @token = request.env["omniauth.auth"].credentials.token
    @graph = Koala::Facebook::API.new(@token)

    if @user.persisted?
      sign_in @user
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
    redirect_to root_path
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def faq
	end

	def contact
	end

	def help
	end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def search
    if params
      @travels = Travel.where(
        origin: params[:origin],
        destination: params[:destination]
      )

      @amount = @travels.size

      @user_id = 1 #current_user.id
      @user = User.find(@user_id)

      @signed_travels = User.find(@user_id).travels.pluck(:id)

      @presenter = TravelSearchPresenter.new(@travels,@signed_travels).to_hash
      @presenter = Kaminari.paginate_array(@presenter).page(params[:page]).per(5)
    end
  end

  def offer
    @user_id =  1 #current_user.id
    @cars = User.find(@user_id).cars # Temporal
    @travels = []
    @cars.each do |car|
      @travels += car.travels
    end

    @travels = @travels.sort_by{|e| e[sort_column]}

    if sort_direction == "desc"
      @travels = @travels.reverse
    end

    @presenter =  TravelOfferedPresenter.new(@travels).to_hash
    @presenter = Kaminari.paginate_array(@presenter).page(params[:page]).per(5)
  end

  def show
    @user_id =  1 #current_user.id
    @travel = Travel.find(params[:id]) # Temporal
    @signed_travels = User.find(@user_id).travels.pluck(:id)

    @presenter =  TravelShowPresenter.new(@travel,@signed_travels).to_hash
  end

  def create
    @user_id = 1 #current_user.id
    @travel = Travel.new(travel_params)
    @signed_travels = User.find(@user_id).travels.pluck(:id)
    @travel.save
    @presenter = TravelShowPresenter.new(@travel,@signed_travels).to_hash
  end

  def update
    @user_id = 1 #current_user.id
    @travel = Travel.find(params[:id])
    @travel.update_attributes(travel_params)
    @signed_travels = User.find(@user_id).travels.pluck(:id)
    @travel.save
    @presenter = TravelShowPresenter.new(@travel,@signed_travels).to_hash
  end

  def destroy
    Travel.find(params[:id]).destroy
  end

private

  def travel_params
      params.require(:travel).permit(
      :car_id,
      :departure,
      :description,
      :origin,
      :destination,
      :available_places)
  end

  def sort_column
    Travel.column_names.include?(params[:sort]) ? params[:sort] : "departure"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/controllers/user_pages_controller.rb
class UserPagesController < ApplicationController
    def offer
    end

    def search
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/travel_helper.rb
module TravelHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to({:sort => column, :direction => direction}, {:class => "travels__results-header-link"}) do
      content_tag(:span, title) +
      content_tag(:span, nil, class: css_class)
    end
  end
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>
    Carmelo © 2016 - powered by The Hipster Cloud
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="header__navbar">
    <div class="header__logo">
      <%= link_to image_tag("logo.png", alt: "Carmelo"), root_path %>
    </div>
    <ul class="header__nav">
      <li class="header__item">
        <%= link_to "¿Cómo Funciona?", root_path, class: "header__link" %>
      </li>
      <li class="header__item">
        <%= link_to "Preguntas Frecuentes", root_path, class: "header__link" %>
      </li>
      <% if current_user %>
      <li class="header__item header__item--profile">
        <div class="header__profile-picture">
          <%= image_tag("profile.png", alt: "Profile picture") %>
        </div>
        <div class="header__profile-links">
          <div><%= current_user.first_name %></div>
          <%= link_to "Perfil del usuario", edit_user_registration_path %>
        </div>
      </li>
      <% else %>
      <li class="header__item header__item--login">
        <%= link_to "Iniciar Sesión", login_path, class: "header__link header__link--login" %>
      </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>"Carmelo.Club | "<%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <div class="app">
    	<%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<% content_for :title, "Test" %>
<article class="home">
  <section class="home__main">
    <div class="home__logo">
      <%= link_to image_tag("logo.png", alt: "Carmelo"), root_path %>
    </div>
    <div class="home__options">
      <%= link_to offer_travels_path, class: "home__option home__option--offer" do %>
        <span>Ofrezco Viaje</span>
      <% end %>
      <%= link_to search_travels_path, class: "home__option home__option--search" do %>
        <span>Necesito Transporte</span>
      <% end %>
    </div>
  </section>
</article>

app/views/static_pages/login.html.erb
<article class="login">
  <section class="login__main">
    <div class="login__logo">
      <%= link_to image_tag("logo.png", alt: "Carmelo"), root_path %>
    </div>
    <div class="login__option">
      <%= link_to "Login con Facebook", user_facebook_omniauth_authorize_path, class: "login__facebook" %>
    </div>
  </section>
</article>

app/views/static_pages/register.html.erb
<article class="register view">
  <section class="register__form-section">
    <form class="register__form">
      <fieldset class="register__form-field register__form-field--name">
        <label class="register__form-label" for="register-name-input">
          Nombre
        </label>
        <input type="text" name="name" placeholder="Nombre" id="register-name-input" required>
        <input type="text" name="lastname" placeholder="Apellido" required>
      </fieldset>
      <fieldset class="register__form-field register__form-field--birthdate">
        <label class="register__form-label" for="register-birthdate-input">
          Fecha de Nacimiento
        </label>
        <input type="number" name="day" placeholder="Día" id="register-birthdate-input" required>
        <input type="number" name="month" placeholder="Mes" required>
        <input type="number" name="year" placeholder="Año" required>
      </fieldset>
      <fieldset class="register__form-field register__form-field--gender">
        <label class="register__form-label">
          Sexo
        </label>
        <div class="register__form-radio">
          <label class="register__form-label" for="female-radio">Femenino</label>
          <input type="radio" name="gender" value="female" id="female-radio" required>
        </div>
        <div class="register__form-radio">
          <label class="register__form-label" for="male-radio">Masculino</label>
          <input type="radio" name="gender" value="male" id="male-radio" required>
        </div>
      </fieldset>
      <fieldset class="register__form-field register__form-field--location">
        <input type="text" name="country" placeholder="Nacionalidad" required>
        <input type="text" name="province" placeholder="Provincia" required>
        <input type="text" name="city" placeholder="Ciudad" required>
      </fieldset>
      <fieldset class="register__form-field register__form-field--phone">
        <label class="register__form-label" for="register-phone-input">
          Teléfono Celular
        </label>
        <input type="tel" name="phone" id="register-phone-input" required>
      </fieldset>
      <fieldset class="register__form-field register__form-field--email">
        <label class="register__form-label" for="register-email-input">
          Dirección de Correo Electrónico Actual
        </label>
        <input type="email" name="email" id="register-email-input" required>
      </fieldset>
      <fieldset class="register__form-field">
        <button type="submit" class="register__form-submit">
          Registrarse
        </button>
      </fieldset>
    </form>
  </section>
</article>

app/views/travels/_header.html.erb
<header class="travels__header">
  <nav class="travels__navbar">
    <ul class="travels__nav">
      <li class="travels__nav-item">
        <%= active_link_to "Buscar", search_travels_path, class: "travels__nav-link" %>
      </li>
      <li class="travels__nav-item">
        <%= active_link_to "Ofrecer", offer_travels_path, class: "travels__nav-link" %>
      </li>
    </ul>
    </nav>
</header>

app/views/travels/offer.html.erb
<article class="travels offer">
  <%= render 'header' %>

  <%= render 'travels/offerPartials/offer-form' %>

  <%= render 'travels/offerPartials/offer-results' %>

  <%= render 'travels/offerPartials/edit-modal' %>

  <%= render 'travels/offerPartials/subscribers-modal' %>

  <%= render 'travels/offerPartials/delete-modal' %>
</article>

app/views/travels/offerPartials/_delete-modal.html.erb
<div
  id="delete-modal"
  class="modal fade"
  tabindex="-1"
  role="dialog"
  aria-labelledby="myModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Eliminar</h3>
      </div>
      <div class="modal-body">
        <span>¿Estás seguro?</span>
      </div>
      <div class="modal-footer">
        <button
          class="modal__submit"
          data-dismiss="modal"
          aria-hidden="true"
        >
          Confirmar
        </button>
      </div>
    </div>
  </div>
</div>

app/views/travels/offerPartials/_edit-modal.html.erb
<div
  id="edit-modal"
  class="modal fade"
  tabindex="-1"
  role="dialog"
  aria-labelledby="myModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Editar</h3>
      </div>
      <div class="modal-body">
        <%= form_tag({controller: "travels", action: "offer"}, {method: "post"}) do %>
          <fieldset class="modal__form-field">
            <%= text_field_tag :origin, nil, placeholder: 'Origen', class: "modal__input" %>
          </fieldset>

          <fieldset class="modal__form-field">
            <%= text_field_tag :destination, nil, placeholder: 'Destino', class: "modal__input" %>
          </fieldset>

          <fieldset class="modal__form-field">
            <%= text_field_tag :model, nil, placeholder: 'Modelo', class: "modal__input" %>
          </fieldset>

          <fieldset class="modal__form-field">
            <input
              id="date_from"
              type="text"
              class="modal__input"
              placeholder="Fecha"
              name="date_from"
              data-provide="datepicker"
              readonly
            >
          </fieldset>
        <% end %>
      </div>
      <div class="modal-footer">
        <fieldset class="modal__form-field">
            <button
              type="submit"
              class="modal__submit"
              data-dismiss="modal"
              aria-hidden="true"
            >
              <span>
                Editar
              </span>
            </button>
          </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/travels/offerPartials/_offer-form.html.erb
<section class="travels__form-section">
  <%= form_tag({controller: "travels", action: "create"}, {method: "post", class: "travels__form"}) do %>
    <fieldset class="travels__form-field">
      <%= label_tag :origin, "De dónde", class: "travels__form-label travels__form-label--finder" %>
      <%= text_field_tag :origin, nil, class: 'travels__form-input', :required => true %>
    </fieldset>

    <fieldset class="travels__form-field">
      <%= label_tag :destination, "A dónde", class: "travels__form-label travels__form-label--finder" %>
      <%= text_field_tag :destination, nil, class: 'travels__form-input', :required => true %>
    </fieldset>

    <fieldset class="travels__form-field">
      <%= label_tag :departure, "Cuándo", class: "travels__form-label travels__form-label--calendar" %>
      <input
        id="departure"
        class="travels__form-input"
        type="text"
        name="departure"
        data-provide="datepicker"
        readonly
        required
      >
    </fieldset>

    <fieldset class="travels__form-field">
      <%= label_tag :car_model, "Modelo de auto", class: "travels__form-label" %>
      <%= text_field_tag :car_model, nil, class: 'travels__form-input', :required => true %>
    </fieldset>

    <fieldset class="travels__form-field">
      <%= label_tag :places, "Lugares", class: "travels__form-label" %>
      <%= number_field_tag :places, nil, within: 1...5, class: 'travels__form-input', :required => true %>
    </fieldset>

    <fieldset class="travels__form-field">
      <button
          type="submit"
          class="travels__form-submit"
      >
        <span>
          Ofrecer
        </span>
      </button>
    </fieldset>
  <% end %>
</section>

app/views/travels/offerPartials/_offer-results.html.erb
<section class="travels__results-section">
  <%= paginate @presenter %>

  <header class="travels__results-header">
    <ul>
      <li class="travels__results-header-column">
        <%= sortable "origin", "Desde" %>
      </li>
      <li class="travels__results-header-column">
        <%= sortable "destination", "Hasta" %>
      </li>
      <li class="travels__results-header-column">
        <%= sortable "departure", "Día" %>
      </li>
      <li class="travels__results-header-column">
        <span>Modelo de Auto</span>
      </li>
      <li class="travels__results-header-column">
        <span>Acciones</span>
      </li>
    </ul>
  </header>

  <ul class="travels__results-list">
    <% @presenter.each do |travel| %>
      <li class="travels__result">
        <ul class="travels__result-info">
          <li class="travels__result-column">
            <span><%= travel["travel_information"]["origin"] %></span>
          </li>
          <li class="travels__result-column">
            <span><%= travel["travel_information"]["destination"] %></span>
          </li>
          <li class="travels__result-column">
            <span><%= travel["travel_information"]["departure"] %></span>
          </li>
          <li class="travels__result-column">
            <span>
              <%= travel["car_information"]["model"] %>
              <%= travel["car_information"]["year"] %>
            </span>
          </li>
          <li class="travels__result-column">
            <button
              class="travels__result-action-button travels__result-action-button--edit"
              data-toggle="modal"
              data-target="#edit-modal"
            >
            </button>
            <button
              class="travels__result-action-button travels__result-action-button--subscribers"
              data-toggle="modal"
              data-target="#subscribers-modal"
            >
            </button>
            <button
              class="travels__result-action-button travels__result-action-button--delete"
              data-toggle="modal"
              data-target="#delete-modal"
            >
            </button>
          </li>
        </ul>
      </li>
    <% end %>
  </ul>
</section>

app/views/travels/offerPartials/_subscribers-modal.html.erb
<div
  id="subscribers-modal"
  class="modal fade"
  tabindex="-1"
  role="dialog"
  aria-labelledby="myModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Suscriptos</h3>
      </div>
      <div class="modal-body">
        <ul class="modal__subscribers-list">
          <li class="modal__subscriber">
            <ul class="modal__subscriber-info">
              <li class="modal__info-column">
                <div class="modal__subscriber-profile-picture">
                  <%= image_tag("profile.png", alt: "Profile picture") %>
                </div>
              </li>
              <li class="modal__info-column">
                <span>Nombre y apellido del suscripto</span>
                <span>28 años fecha de nacimiento 00/00/00</span>
              </li>
            </ul>
          </li>
          <li class="modal__subscriber">
            <ul class="modal__subscriber-info">
              <li class="modal__info-column">
                <div class="modal__subscriber-profile-picture">
                  <%= image_tag("profile.png", alt: "Profile picture") %>
                </div>
              </li>
              <li class="modal__info-column">
                <span>Nombre y apellido del suscripto</span>
                <span>28 años fecha de nacimiento 00/00/00</span>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button
          class="modal__submit"
          data-dismiss="modal"
          aria-hidden="true"
        >
          Cerrar
        </button>
      </div>
    </div>
  </div>
</div>

app/views/travels/offered.html.erb
<article class="travels offer">
  <%= render 'header' %>

  <%= render 'travels/offerPartials/offer-form' %>

  <%= render 'travels/offerPartials/offer-results' %>

  <%= render 'travels/offerPartials/edit-modal' %>

  <%= render 'travels/offerPartials/subscribers-modal' %>

  <%= render 'travels/offerPartials/delete-modal' %>
</article>

app/views/travels/search.html.erb
<article class="travels search">
  <%= render 'header' %>

  <%= render 'travels/searchPartials/search-form' %>

  <% if @travels.present? %>
    <section class="travels__results-section">
      <%= render 'travels/searchPartials/search-filters' %>

      <%= render 'travels/searchPartials/search-results' %>
    </section>
  <% end %>
</article>

app/views/travels/searchPartials/_search-filters.html.erb
<section class="travels__filter-section">
  <header class="travels__filter-header">
    <div class="travels__filter-header-left">
      <span class="travels__filter-results-amount">
        <%= @amount %>
      </span>
      <span>Servicios encontrados</span>
    </div>
    <div class="travels__filter-header-right">
      <button
        class="travels__filter-button"
        data-toggle="collapse"
        data-target="#filters"
        aria-expanded="false"
        aria-controls="filters"
      >
        <span class="glyphicon glyphicon-filter"></span>
        <span>Filtrar resultados</span>
      </button>
    </div>
  </header>

  <div id="filters" class="collapse">
    <form class="travels__filter-form">
      <fieldset class="travels__filter">
        <label class="travels__filter-label">Edad</label>
        <div class="travels__filter-slider-container">
          <div id="travels__filter-age-slider"></div>
        </div>
        <span id="minAge" class="travels__filter-min"></span>
        <span id="maxAge" class="travels__filter-max"></span>
      </fieldset>
      <fieldset class="travels__filter">
        <label class="travels__filter-label">Modelo de Auto</label>
        <div class="travels__filter-slider-container">
          <div id="travels__filter-model-slider"></div>
        </div>
        <span id="minModel" class="travels__filter-min"></span>
        <span id="maxModel" class="travels__filter-max"></span>
      </fieldset>
      <fieldset class="travels__filter">
        <label class="travels__filter-label">Sexo</label>
        <div class="travels__filter-checkbox">
          <input type="checkbox" name="gender" value="female" id="female-checkbox">
          <label class="travels__filter-label" for="female-checkbox">Femenino</label>
        </div>
        <div class="travels__filter-checkbox">
          <input type="checkbox" name="gender" value="male" id="male-checkbox">
          <label class="travels__filter-label" for="male-checkbox">Masculino</label>
        </div>
      </fieldset>
    </form>
  </div>
</section>

app/views/travels/searchPartials/_search-form.html.erb
<section class="travels__form-section">
  <%= form_tag({controller: "travels", action: "search"}, {method: "get", class: "travels__form"}) do %>
    <fieldset class="travels__form-field">
      <%= label_tag :origin, "De dónde", class: "travels__form-label travels__form-label--finder" %>
      <%= text_field_tag :origin, nil, class: 'travels__form-input', :required => true %>
    </fieldset>

    <fieldset class="travels__form-field">
      <%= label_tag :destination, "A dónde", class: "travels__form-label travels__form-label--finder" %>
      <%= text_field_tag :destination, nil, class: 'travels__form-input', :required => true %>
    </fieldset>
    <fieldset class="travels__form-field">
      <%= label_tag :departure, "Cuándo", class: "travels__form-label travels__form-label--calendar" %>
      <input
        id="departure"
        class="travels__form-input"
        type="text"
        name="departure"
        data-provide="datepicker"
        readonly
        required
      >
    </fieldset>
    <fieldset class="travels__form-field">
      <button
        type="submit"
        class="travels__form-submit"
      >
        <span>
          Buscar
        </span>
      </button>
    </fieldset>
  <% end %>
</section>

app/views/travels/searchPartials/_search-results.html.erb
<section class="travels__results">
  <%= paginate @presenter %>

  <header class="travels__results-header">
    <ul>
      <li class="travels__results-header-column">
        <span>Foto</span>
      </li>
      <li class="travels__results-header-column">
        <%= sortable "first", "Nombre" %>
      </li>
      <li class="travels__results-header-column">
        <%= sortable "first", "Edad" %>
      </li>
      <li class="travels__results-header-column">
        <span>Modelo de Auto</span>
      </li>
    </ul>
  </header>

  <ul class="travels__results-list">
    <% @presenter.each do |travel| %>
      <li class="travels__result">
        <ul class="travels__result-info">
          <li class="travels__result-column">
            <div class="travels__result-profile-picture">
              <%= image_tag "#{travel["user_information"]["facebook_image_url"]}", alt: "Profile picture" %>
            </div>
          </li>
          <li class="travels__result-column">
            <span><%= travel["user_information"]["firstname"] %></span>
            <span><%= travel["user_information"]["lastname"] %></span>
          </li>
          <li class="travels__result-column">
            <span><%= travel["user_information"]["age"] %></span>
          </li>
          <li class="travels__result-column">
            <span>
              <%= travel["car_information"]["model"] %>
              <%= travel["car_information"]["year"] %>
            </span>
          </li>
        </ul>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %>
    <%= f.text_area :first %>
  </div>

  <div class="field">
    <%= f.label :last %>
    <%= f.text_area :last %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>